### ISSUE TITLE
vs2019 - Cannot update from version 2.7.41 to version 2.8.44

### ISSUE THREAD

**Issue by LaraSQP** [mrlacey/CommentLinks#34]
The "Manage Extensions" dialog of vs2019 shows the update.

However, after closing vs2019, the VSIX installer reports that:

"This extension is not installable on any currently installed products."

Which on my machine include vs2017, vs2019, vs2022.

The Install Log follows:

```
12/17/2021 11:42:42 AM - Microsoft VSIX Installer
12/17/2021 11:42:42 AM - -------------------------------------------
12/17/2021 11:42:42 AM - vsixinstaller.exe version:
12/17/2021 11:42:42 AM - 17.0.5226-preview5
12/17/2021 11:42:42 AM - -------------------------------------------
12/17/2021 11:42:42 AM - Command line parameters:
12/17/2021 11:42:42 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\vsixinstaller.exe,/appidinstallpath:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\devenv.exe,/skuName:Community,/skuVersion:16.11.31829.152,/appidname:Microsoft Visual Studio Community 2019,/culture:en-US,/noep,C:\Users\Morgan\AppData\Local\Temp\VSIX3mnggllk.vsix
12/17/2021 11:42:42 AM - -------------------------------------------
12/17/2021 11:42:42 AM - Microsoft VSIX Installer
12/17/2021 11:42:42 AM - -------------------------------------------
12/17/2021 11:42:42 AM - Initializing Install...
12/17/2021 11:42:43 AM - Extension Details...
12/17/2021 11:42:43 AM - 	Identifier         : CommentLinks.bd536c05-2af9-4995-b067-56fa2bb88e31
12/17/2021 11:42:43 AM - 	Name               : CommentLinks
12/17/2021 11:42:43 AM - 	Author             : Matt Lacey
12/17/2021 11:42:43 AM - 	Version            : 2.8.44
12/17/2021 11:42:43 AM - 	Description        : Create links in comments between any files.
12/17/2021 11:42:43 AM - 	Locale             : en-US
12/17/2021 11:42:43 AM - 	MoreInfoURL        : https://github.com/mrlacey/CommentLinks
12/17/2021 11:42:43 AM - 	InstalledByMSI     : False
12/17/2021 11:42:43 AM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
12/17/2021 11:42:43 AM - 
12/17/2021 11:42:43 AM - 	SignatureState     : Unsigned
12/17/2021 11:42:43 AM - 	Supported Products : 
12/17/2021 11:42:43 AM - 		Microsoft.VisualStudio.Community
12/17/2021 11:42:43 AM - 			Version : [17.0,18.0)
12/17/2021 11:42:43 AM - 			ProductArchitecture : amd64
12/17/2021 11:42:43 AM - 
12/17/2021 11:42:43 AM - 	References         : 
12/17/2021 11:42:43 AM - 		-------------------------------------------------------
12/17/2021 11:42:43 AM - 		Identifier   : Microsoft.VisualStudio.MPF.17.0
12/17/2021 11:42:43 AM - 		Name         : Visual Studio MPF 17.0
12/17/2021 11:42:43 AM - 		Version      : [17.0,18.0)
12/17/2021 11:42:43 AM - 		MoreInfoURL  : 
12/17/2021 11:42:43 AM - 		Nested       : No
12/17/2021 11:42:43 AM - 
12/17/2021 11:42:43 AM - 	Prerequisites      : 
12/17/2021 11:42:43 AM - 		-------------------------------------------------------
12/17/2021 11:42:43 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
12/17/2021 11:42:43 AM - 		Name         : Visual Studio core editor
12/17/2021 11:42:43 AM - 		Version      : [17.0,)
12/17/2021 11:42:43 AM - 
12/17/2021 11:42:43 AM - Signature Details...
12/17/2021 11:42:43 AM - 	Extension is not signed.
12/17/2021 11:42:43 AM - 
12/17/2021 11:42:43 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.ComputeInstallableExtensions(IStateData stateData, Boolean isRepairSupported, Boolean isExtensionPack, IDictionary`2 skuDataMapping, IList`1 installableExtensionsPaths)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

```

**Comment by mrlacey** [comment]
This looks like the CI build (from vsixgallery.com) am I right?

Seems I forgot about this. :(
I'm actually surprised it was built and released at all as it was configured to use the VS2017 image to build for VS2022 which I haven't seen work before.

However, I've just installed 2.8.44 in an instance of VS2022 (Version 17.1.0. Preview 1.1) without issue.

Did you try and install directly from the website or do you have the Open VSIX gallery set up as an extension source within VS? (like below)

![image](https://user-images.githubusercontent.com/189547/146524613-129a66f2-b828-4418-bfdf-e9813efb4826.png)

I suspect this issue may be due to how I've changed from having one extension to having two.

There are now separate entries for the version that supports **VS2017 & VS2019** [[Marketplace](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.CommentLinks2019)] [[VSIXGallery](https://www.vsixgallery.com/extension/CommentLinks2019.bd546c05-2af9-4995-b067-57fa2bb88e31)]
And a version that supports **VS2022** [[Marketplace](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.CommentLinks)] [[VSIXGallery](https://www.vsixgallery.com/extension/CommentLinks.bd536c05-2af9-4995-b067-56fa2bb88e31)]

If you already have the old version installed in VS2019 you may need to uninstall it there before you can install the new versions. :/

**Comment by LaraSQP** [comment]
Yes, it was through vsixgallery.com and the "Manage Extensions" dialog.

I uninstalled the vs2019 version and then installed again without a problem

Same with vs2022.

Thank you.

**Comment by mrlacey** [comment]
Glad you got it sorted. sorry about the faff. It's because I didn't want to create a new version for 2022 that used a different name :(

**Comment by LaraSQP** [comment]
I get it.
