### ISSUE TITLE
Error linking from txt file to xaml file?

### ISSUE THREAD

**Issue by hawkerm** [mrlacey/CommentLinks#47]
VS 17.4.2

Error's not providing much detail:
```
Error in OnClick
fullPath
Microsoft.VisualStudio.Shell.15.0
   at Microsoft.VisualStudio.Shell.VsShellUtilities.OpenDocument(IServiceProvider provider, String fullPath, Guid logicalView, IVsUIHierarchy& hierarchy, UInt32& itemID, IVsWindowFrame& windowFrame, IVsTextView& view)
   at CommentLinks.CommentLinkAdornment.<<OnClick>g__OpenFileAsync|11_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommentLinks.CommentLinkAdornment.<OnClick>d__11.MoveNext()
```

Image of source location and target location highlighted in Solution Explorer:

![image](https://user-images.githubusercontent.com/8959496/205434412-d34b4f72-a35e-4ab6-a520-708ec496d07c.png)

Not really sure what's happening, I checked that links from other files were able to work.

**Comment by mrlacey** [comment]
Fix coming tomorrow.

It turns out the problem related to VS not being able to resolve the path correctly.
I'm adding a fix for this.
You may still need to also update the path to be relative `link:../../ComputeSharp.SwapChain.WinUI/Views/MainWindow.xaml`

![image](https://user-images.githubusercontent.com/189547/205751689-b279219c-858e-4e2c-93c8-f7d91a54a413.png)

**Comment by mrlacey** [comment]
Version 2.14 is now in the marketplace and should fix this issue. Let me know if you find anything else that doesn't work as expected.
