### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by hh-cc-2024** [mrlacey/CommentLinks#55]
I have tried to install in VS2022 17.8.3. Other extensions install just fine. The log file has this error:

> 1/8/2024 2:26:21 PM - Install Error : System.InvalidOperationException: Cannot find setup engine instance.
   at Microsoft.VisualStudio.ExtensionManager.SetupEngineUtility.GetCurrentSetupInstance(IEngineHost engineHost)
   at Microsoft.VisualStudio.ExtensionManager.SetupEngineService.CreateEngine(IEngineHost engineHost, IServiceProvider serviceProvider, InstallFlags installFlags)
   at Microsoft.VisualStudio.ExtensionManager.InstallModule.PerformSetupEngineInstall(InstallableExtensionImpl extensionToInstall, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.InstallModule.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.InstallModule.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.InstallModule.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

**Comment by mrlacey** [comment]
@hh-cc-2024 did you try installing from within Visual Studio, or did you download the file from the marketplace and then launch that to start the installer?

I'll try a fresh reinstall to try and duplicate what you're doing/seeing.

The exception is internal to the VSInstaller and so shouldn't have any issue with the extension.
Do you have any pending reboots or Visual Studio instances that haven't shut down correctly?
Restarting the machine may unblock it. :/

**Comment by mrlacey** [comment]
[Re]installs fine for me, on multiple machines.

Please reopen this if repairing VS doesn't solve it and you have more information about how you're trying to install it.
